[package]
name = "twitter-stream"
version = "0.1.5"
authors = ["Daiki Mizukami"]
license = "MIT"
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
homepage = "https://github.com/d12i/twitter-stream-rs"
repository = "https://github.com/d12i/twitter-stream-rs"
documentation = "https://docs.rs/twitter-stream/0.1.5/twitter_stream/"
description = """
A library for listening on Twitter Streaming API.
"""

[dependencies]
chrono = { version = ">= 0.2, < 0.4", features = ["serde"] }
flate2 = "0.2"
futures = "0.1"
hyper = "0.10"
hyper-native-tls = { version = "0.2", optional = true }
hyper-openssl = { version = "0.2", optional = true }
hyper-rustls = { version = "0.3", optional = true }
oauthcli = "1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.3"

[features]
default = ["native-tls"]
native-tls = ["hyper-native-tls"]
openssl = ["hyper-openssl"]
rustls = ["hyper-rustls"]
