[package]
name = "twitter-stream"
version = "0.8.0"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
homepage = "https://github.com/tesaguri/twitter-stream-rs"
repository = "https://github.com/tesaguri/twitter-stream-rs"
documentation = "https://docs.rs/twitter-stream/0.8.0/twitter_stream/"
description = """
A library for listening on Twitter Streaming API.
"""

[dependencies]
bytes = "0.4.4"
cfg-if = "0.1"
futures = "0.1.4"
http = "0.1.11"
hyper = "0.12"
libflate = "0.1.15"
oauth1-request = "0.1"
tokio = "0.1"
tokio-timer = "0.2.2"
egg-mode = { version = "0.12", optional = true }
hyper-openssl = { version = "0.6", optional = true }
hyper-rustls = { version = "0.14", optional = true }
hyper-tls = { version = "0.3", optional = true }
native-tls = { version = "0.2", optional = true }
oauthcli = { version = "1", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
tweetust = { version = "0.9", optional = true }

[features]
default = ["runtime", "tls"]
# `runtime` feature does nothing useful for now, but this feature is
# necessary for the crate to compile, leaving possibility for future extension.
runtime = ["hyper/runtime"]
tls = ["hyper-tls", "native-tls"]
tls-openssl = ["hyper-openssl"]
tls-rustls = ["hyper-rustls"]
use-tweetust = ["oauthcli", "tweetust"]

[[example]]
name = "echo_bot"
required-features = ["serde", "use-tweetust"]

[dev-dependencies]
# examples/echo_bot
serde_json = "1"
tweetust = "0.9"
twitter-stream-message = "0.3"
