[package]
name = "twitter-stream"
edition = "2018"
version = "0.10.0-alpha.2"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
homepage = "https://github.com/tesaguri/twitter-stream-rs"
repository = "https://github.com/tesaguri/twitter-stream-rs"
documentation = "https://docs.rs/twitter-stream/0.10.0-alpha.2/twitter_stream/"
description = """
A library for listening on Twitter Streaming API.
"""

[dependencies]
async-compression = { version = "0.1.0-alpha.1", default-features = false, features = ["gzip", "stream"] }
bytes = "0.4.4"
cfg-if = "0.1"
futures-core-preview = "0.3.0-alpha.17"
futures-executor-preview = "0.3.0-alpha.17"
futures-util-preview = "0.3.0-alpha.17"
http = "0.1.11"
hyper = { version = "0.13.0-alpha.2", default-features = false, features = ["unstable-stream"] }
memchr = "2"
oauth = { version = "0.3.0", package = "oauth1-request" }
string = "0.2"
egg-mode = { version = "0.13", optional = true }
hyper-tls = { version = "0.4.0-alpha.1", optional = true }
oauthcli = { version = "1", optional = true }
static_assertions = "0.3"
tokio = { version = "0.2.0-alpha.1", optional = true }
tokio-timer = { version = "0.3.0-alpha.1", optional = true }
tweetust-pkg = { version = "0.10", optional = true, package = "tweetust" }

[features]
default = ["runtime", "tls"]
runtime = ["hyper/runtime", "tokio", "tokio-timer"]
tls = ["hyper-tls", "runtime"]
tweetust = ["oauthcli", "tweetust-pkg"]

[[example]]
name = "echo_bot"
required-features = ["tweetust"]

[dev-dependencies]
futures-preview = { version = "0.3.0-alpha.17" }
version-sync = "0.8"
# examples/echo_bot
json = { version = "1", package = "serde_json" }
serde = { version = "1", features = ["derive"] }
