[workspace]
members = [
  "twitter-stream",
  "twitter-stream-message",
  "examples/echo_bot",
]

[replace]
"twitter-stream:0.4.0" = { path = "twitter-stream" }
"twitter-stream-message:0.1.0" = { path = "twitter-stream-message" }
