[package]
name = "twitter-streams"
version = "0.1.0"
authors = ["daiki"]

[dependencies]
futures = "*"
hyper = { version = "*", default-features = false }
log = "*"
oauthcli = { version = "*", features = ["hyper"] }
serde_json = "*"
url = "*"

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
security-framework = ["hyper/security-framework"]
