[package]
name = "twitter-stream"
version = "0.2.0"
authors = ["Daiki Mizukami"]
license = "MIT"
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
homepage = "https://github.com/d12i/twitter-stream-rs"
repository = "https://github.com/d12i/twitter-stream-rs"
documentation = "https://docs.rs/twitter-stream/0.2.0/twitter_stream/"
description = """
A library for listening on Twitter Streaming API.
"""

[dependencies]
bytes = "0.4"
chrono = { version = ">= 0.2, < 0.4", features = ["serde"] }
futures = "0.1"
hyper = { version = "0.11.0-a", git = "https://github.com/hyperium/hyper/" }
hyper-tls = { version = "0.0", git = "https://github.com/hyperium/hyper-tls/" }
lazy_static = "0.2"
oauthcli = "1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
tokio-core = "0.1"
url = "1.0"
egg-mode = { version = "0.8", optional = true }
tweetust = { version = "0.6", optional = true }

[[example]]
name = "echo_bot"
