[package]
name = "twitter-stream"
version = "0.1.5"
authors = ["Daiki Mizukami"]
license = "MIT"
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
homepage = "https://github.com/d12i/twitter-stream-rs"
repository = "https://github.com/d12i/twitter-stream-rs"
documentation = "https://docs.rs/twitter-stream/0.1.5/twitter_stream/"
description = """
A library for listening on Twitter Streaming API.
"""

[dependencies]
chrono = { version = ">= 0.2, < 0.4", features = ["serde"] }
flate2 = "0.2"
futures = "0.1"
hyper = "0.10"
oauthcli = "1.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.3"
egg-mode = { version = "0.8", optional = true }
tweetust = { version = "0.5", optional = true }
hyper-native-tls = { version = "0.2", optional = true }
native-tls = { version = "0.1", optional = true }
hyper-openssl = { version = "0.2", optional = true }
openssl = { version = "0.9", optional = true }
hyper-rustls = { version = "0.3", optional = true }

[features]
default = ["tls-native-tls"]
tls-native-tls = ["hyper-native-tls", "native-tls", "tls-failable"]
tls-openssl = ["hyper-openssl", "openssl", "tls-failable"]
tls-rustls = ["hyper-rustls", "tls"]

# For internal use:
tls = []
tls-failable = ["tls"]
