[package]
name = "twitter-stream"
version = "0.1.0"
authors = ["daiki"]
readme = "README.md"
keywords = ["twitter"]
categories = ["api-bindings"]
license = "MIT"

[dependencies]
chrono = { version = "*", features = ["serde"] }
flate2 = "*"
futures = "*"
hyper = { version = "*", default-features = false }
hyper-native-tls = { version = "*", optional = true }
hyper-openssl = { version = "*", optional = true }
hyper-rustls = { version = "*", optional = true }
log = "*"
oauthcli = { version = "^1.0.3", features = ["hyper"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
url = "*"

[features]
default = ["rustls"]
native-tls = ["hyper-native-tls"]
openssl = ["hyper-openssl"]
rustls = ["hyper-rustls"]
