[workspace]
members = [
  "twitter-stream",
  "twitter-stream-message",
  "examples/echo_bot",
]

[replace]
"twitter-stream:0.6.1" = { path = "twitter-stream" }
"twitter-stream-message:0.3.0" = { path = "twitter-stream-message" }
