[package]
name = "twitter-stream"
version = "0.1.0"
authors = ["daiki"]

[dependencies]
chrono = { version = "*", features = ["serde"] }
futures = "*"
hyper = { version = "*", default-features = false }
log = "*"
oauthcli = { version = "*", features = ["hyper"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
url = "*"

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
security-framework = ["hyper/security-framework"]
